-- FastQuote Decal - Supabase Database
-- Jalankan file ini di Supabase > SQL Editor > New query > Run

create table if not exists public.calculator_history (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    created_by uuid references auth.users(id) on delete set null,

    waktu text,
    tanggal date,
    bulan text,

    nama text,
    bahan text,
    laminasi text,
    dimensi text,

    lebar numeric default 0,
    panjang numeric default 0,
    qty integer default 1,
    cutting boolean default false,

    biaya_tambahan numeric default 0,
    margin_pct numeric default 0,
    num_modal numeric default 0,
    num_jual numeric default 0
);

alter table public.calculator_history enable row level security;

drop policy if exists "Semua admin login bisa lihat riwayat toko" on public.calculator_history;
create policy "Semua admin login bisa lihat riwayat toko"
on public.calculator_history
for select
to authenticated
using (true);

drop policy if exists "Admin login bisa tambah riwayat toko" on public.calculator_history;
create policy "Admin login bisa tambah riwayat toko"
on public.calculator_history
for insert
to authenticated
with check (auth.uid() = created_by);

drop policy if exists "Semua admin login bisa hapus riwayat toko" on public.calculator_history;
create policy "Semua admin login bisa hapus riwayat toko"
on public.calculator_history
for delete
to authenticated
using (true);

drop policy if exists "Semua admin login bisa update riwayat toko" on public.calculator_history;
create policy "Semua admin login bisa update riwayat toko"
on public.calculator_history
for update
to authenticated
using (true)
with check (true);
